### ISSUE TITLE
Cannot install from setup.py file on ARM device.

### ISSUE THREAD

**Issue by chiehpower** [shellcheck-py/shellcheck-py#43]
Hi, 

- my env is on ARM device (Jetson device).
- OS: ubuntu18.04
- Python 3.8

I was trying to install it from setup.py.

Here are my steps.
```
git clone https://github.com/shellcheck-py/shellcheck-py.git
cd shellcheck-py/
python3.8 setup.py build
```

Here was the output:
```
root@fcf09b4b8614:~/shellcheck-py# python3.8 setup.py build  
running build
running fetch_binaries
Traceback (most recent call last):
  File "setup.py", line 171, in <module>
    setup(version=f'{SHELLCHECK_VERSION}.{PY_VERSION}', cmdclass=command_overrides)
  File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "setup.py", line 118, in run
    archive = download(url, sha256)
  File "setup.py", line 62, in download
    raise ValueError(f'sha256 mismatch, expected {sha256}, got {checksum}')
ValueError: sha256 mismatch, expected a12bdfe0f95811ad6c0a091006b919b2834b0619b460cfa596f557edd62e45ab, got 9f47bbff5624babfa712eb9d64ece14c6c46327122d0c54983f627ae3a30a4ac
```

Thank you so much in advance!!

**Comment by asottile** [comment]
@odidev looks like you broke this?

**Comment by chiehpower** [comment]
The version of `0.8.0.1` can work by `pip` installation.
Thanks for my colleague helping. lol

**Comment by odidev** [comment]
@asottile, it's my mistake. Somehow, I placed the wrong checksum. Raised [PR](https://github.com/shellcheck-py/shellcheck-py/pull/44) again to fix this.
