### ISSUE TITLE
Cannot use as a pre-commit hook on macOS w/ M1 chip

### ISSUE THREAD

**Issue by sadikkuzu** [shellcheck-py/shellcheck-py#57]
Hi,

When shellcheck-py is used as a pre-commit hook, the following log occurs on macOS w/ M1 chip.
Any suggestions will be greatly appreciated.

Thanks in advance.

```
running build
running fetch_binaries
Traceback (most recent call last):
  File "setup.py", line 176, in <module>
    setup(version=f'{SHELLCHECK_VERSION}.{PY_VERSION}', cmdclass=command_overrides)
  File "/Users/***/.pyenv/versions/3.7.12/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/Users/***/.pyenv/versions/3.7.12/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/Users/***/.pyenv/versions/3.7.12/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/Users/***/.pyenv/versions/3.7.12/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/Users/***/.pyenv/versions/3.7.12/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/Users/***/.pyenv/versions/3.7.12/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/Users/***/.pyenv/versions/3.7.12/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 136, in run
    self.run_command(cmd_name)
  File "/Users/***/.pyenv/versions/3.7.12/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/***/.pyenv/versions/3.7.12/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/Users/***/.pyenv/versions/3.7.12/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "setup.py", line 124, in run
    data = extract(url, archive)
  File "setup.py", line 75, in extract
    with tarfile.open(fileobj=bio) as tarf:
  File "/Users/***/.pyenv/versions/3.7.12/lib/python3.7/tarfile.py", line 1580, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

`.pre-commit-config.yaml`:

```yaml
repos:
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
    -   id: shellcheck
```

![image](https://user-images.githubusercontent.com/23168063/163670271-a409d809-c18e-45f8-8bd0-b75645318581.png)

**Comment by asottile** [comment]
it works fine for me on M1, you've probably compiled your own python (and poorly) missing the necessary lzma module (as is typical with pyenv)
